# Generated by Django 5.0.3 on 2024-04-03 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('experience_level', models.CharField(max_length=100)),
                ('salary_range', models.CharField(max_length=100)),
                ('posted_date', models.DateField()),
                ('category', models.CharField(default='default_category', max_length=100)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_connect.technology')),
            ],
        ),
    ]
