# Generated by Django 5.0.4 on 2024-04-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('salary_range', models.CharField(max_length=100)),
                ('posted_date', models.DateField()),
                ('categories', models.ManyToManyField(blank=True, to='tech_connect.category')),
                ('experience_levels', models.ManyToManyField(blank=True, to='tech_connect.experiencelevel')),
                ('technologies', models.ManyToManyField(blank=True, to='tech_connect.technology')),
            ],
        ),
    ]
