# Generated by Django 5.0.3 on 2024-04-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='category',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
