# Generated by Django 5.0.3 on 2024-04-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_connect', '0002_alter_jobposting_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='technology',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='tech_connect.technology'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='experiences',
            field=models.ManyToManyField(blank=True, to='tech_connect.experience'),
        ),
    ]
