# Generated by Django 5.0.4 on 2024-04-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_connect', '0004_rename_experience_experiencelevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='category',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='categories',
            field=models.ManyToManyField(blank=True, to='tech_connect.category'),
        ),
    ]
